included:
  - SuperDoer

excluded:
  - SuperDoer/Resources
  - SuperDoer/Config

disabled_rules:
  - type_body_length
  - function_body_length
  - todo
#  - cyclomatic_complexity

opt_in_rules:
  - empty_count
  - closure_spacing
  - discouraged_direct_init
  - multiline_arguments
  - multiline_parameters
  - redundant_nil_coalescing
#  - trailing_whitespace

# Настройки отдельных правил
line_length:
  warning: 120
  error: 160
  ignores_urls: true

type_name:
  min_length: 3
  max_length: 40
  allowed_symbols: ["_"]

identifier_name:
  min_length: 2
  max_length: 40

cyclomatic_complexity:
  warning: 15
  error: 30

trailing_comma:
  mandatory_comma: true

file_length:
  warning: 600
  error: 1000

reporter: "xcode"
