included:
  - SuperDoer

excluded:
  - SuperDoer/Resources
  - SuperDoer/Config

disabled_rules:
  - todo
  - empty_count
  - closure_parameter_position
  - for_where
#  - cyclomatic_complexity

opt_in_rules:
  - closure_spacing
  - discouraged_direct_init
  - multiline_arguments
  - multiline_parameters
  - redundant_nil_coalescing
  - trailing_whitespace

# Настройки отдельных правил
line_length:
  warning: 120
  error: 160
  ignores_urls: true
  ignores_comments: true
  ignores_interpolated_strings: true

type_name:
  min_length: 3
  max_length: 40
  allowed_symbols: ["_"]

identifier_name:
  min_length: 2
  max_length: 40

cyclomatic_complexity:
  warning: 15
  error: 30

trailing_comma:
  mandatory_comma: true

file_length:
  warning: 600
  error: 1000

large_tuple:
  warning: 3
  error: 5

reporter: "xcode"
